crowdfunder/config/routes.rb
Crowdfunder::Application.routes.draw do
  get "comments/new"
  get "comments/create"
  get "comments/edit"
  get "comments/update"
  get "comments/destroy"
  post 'campaigns/tagged' => 'campaigns#tagged', :as => 'tagged'

  resources :users, :except => [:index]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :campaigns  do
      resources :comments, :except => [:index, :show]
      resources :breakpoints, :except => [:index] do
        resources :contributions, :except => [:index, :edit, :new]
    end
  end

   root 'campaigns#index'
end

crowdfunder/app/models/breakpoint.rb
class Breakpoint < ActiveRecord::Base
	has_many :contributions
  has_many :user, through: :contributions
  belongs_to :campaign

  validates :title, :description, :estimated_delivery, :value_in_cents, :campaign_id, presence: :true
  validates :value_in_cents, numericality: {only_integer: :true}
  validate :number_available_is_nil_or_int


  def number_available_is_nil_or_int
    if number_available.present? && number_available.class != Fixnum
      errors.add(:number_available, "must be integer or left blank if not applicable")
    end
  end
end

crowdfunder/app/controllers/breakpoints_controller.rb
class BreakpointsController < ApplicationController

	before_filter :load_campaign
	before_filter :ensure_logged_in

	def create
		@breakpoint = @campaign.breakpoints.new(breakpoint_params)

		if @breakpoint.save
			redirect_to campaign_path(@campaign), notice: 'breakpoint created!'
		else
	    redirect_to campaign_path(@campaign), notice: "something went wrong"
		end

	end

  private
  def breakpoint_params
  	params.require(:breakpoint).permit(:title, :description, :estimated_delivery, :value_in_cents, :campaign_id, :number_available)
  end

  def load_campaign
  	@campaign = Campaign.find(params[:campaign_id])
  end

end

crowdfunder/app/helpers/breakpoints_helper.rb
module BreakpointsHelper
end

crowdfunder/app/views/breakpoints/_breakpoint.html.erb
<div class = "breakpoint" id="b_<%= breakpoint.id %>">
  <ul>
    <li><h3>$<%= breakpoint.value_in_cents %></h3></li>
    <li><%= breakpoint.number_available - breakpoint.contributions.count %> left of <%= breakpoint.number_available %></li>
    <li><h6><%= breakpoint.title %></h6></li>
    <li><%= breakpoint.description %></li>
    <li>Number taken: <%= breakpoint.contributions.count %></li>
    <li>Estimated delivery: <%= breakpoint.estimated_delivery %></li>
    <% if current_user && current_user.breakpoints.include?(breakpoint)%>
      <li class="backed">You have pledged this perk!</li>
    <% elsif current_user %>
      <%= button_tag 'Contribute here!', {:class => 'contribute-button', data: campaign_breakpoint_contributions_path(breakpoint.campaign, breakpoint)} %>
    <% else %>
      <p>Log in or sign up to contribute.</p>
    <% end %>
  </ul>
</div>

crowdfunder/app/views/breakpoints/_breakpoint_form.html.erb
<div class="breakpoint-form">
<h2>Add breakpoint</h2>
<%= form_for ([@campaign, @breakpoint]) do |f| %>
	<% if @breakpoint.errors.any?  %>
		<div id = "error_explanation">
			<h2><%= pluralize(@breakpoint.errors.count, "error") %> prevented this breakpoint from being saved.</h2>
			<ul>
				<% @breakpoint.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class = "field">
		<p>
			<%= f.label :title %><br/>
			<%= f.text_area :title %>
		</p>
		<p>
			<%= f.label :description %><br/>
			<%= f.text_area :description %>
		</p>
		<p>
			<%= f.label :estimated_delivery %><br/>
			<%= f.date_field :estimated_delivery %>
		</p>
		<p>
			<%= f.label :value_in_cents %><br/>
			<%= f.text_field :value_in_cents %>
		</p>
		<p>
			<%= f.label :number_available %><br/>
			<%= f.text_field :number_available %>
		</p>
	</div>

	<div class = "actions">
		<%= f.submit %>
	</div>
<% end %>
</div>