crowdfunder/config/routes.rb
Crowdfunder::Application.routes.draw do
  get "comments/new"
  get "comments/create"
  get "comments/edit"
  get "comments/update"
  get "comments/destroy"
  post 'campaigns/tagged' => 'campaigns#tagged', :as => 'tagged'

  resources :users, :except => [:index]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :campaigns  do
      resources :comments, :except => [:index, :show]
      resources :breakpoints, :except => [:index] do
        resources :contributions, :except => [:index, :edit, :new]
    end
  end

   root 'campaigns#index'
end

crowdfunder/app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "CrowdFunder" %></title>
    <link href='http://fonts.googleapis.com/css?family=Codystar' rel='stylesheet' type='text/css'>
  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>
  <body>


<nav class="top-bar small-12" data-topbar>
  <ul class="title-area">
    <li>
      <div class="name">
        <p><a href="<%= campaigns_path %>">CrowdFunder</a></p>
      </div>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="divider"></li>
      <li><%= link_to 'Home', campaigns_path %></li>
      <% if current_user %>
        <li class="has-dropdown">
        <a href="#"><%= current_user.name %> | <%= current_user.email %></a>
          <ul class="dropdown">
            <li><a href="<%= user_path(current_user) %>">My profile</a></li>
            <li><a href="<%= edit_user_path(current_user)%>">Edit account</a></li>
            <li><%= link_to 'Log out', session_path("blah"), :method => :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to 'login', new_session_path %></li>
        <li><%= link_to 'signup', new_user_path %></li>
      <% end %>
    </ul>
  </section>
</nav>

 <div class="row">
      <div class="columns small-12">

    <% if flash[:notice] %>
      <div class="alert-box"><%= flash[:notice] %></div>
    <% end %>

    <% if flash[:alert] %>
      <div class="alert-box"><%= flash[:alert] %></div>
    <% end %>

    <%= yield %>
    </div>
</div>

    <%= javascript_include_tag "application" %>
  </body>
</html>